name: simple_simple_todo
description: "A simple todo app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  result_dart: ^2.0.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
