name: simple_simple_todo
description: "A simple todo app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  sqflite: ^2.4.1
  result_dart: ^2.0.0
  go_router: ^14.8.1
  get_it: ^8.0.3
  path: ^1.9.0
dev_dependencies:
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
